window.visualHookData = [
  {
    "id": "7318924509522791710-002",
    "videoId": "7318924509522791710",
    "creator": "@thenaturalnadine",
    "title": "Banana Peel Skincare Scrub",
    "clipPath": "../content/visual-hook-mining/clips/thenaturalnadine__banana-peel-skincare-scrub__7318924509522791710_v3_31flashlite/beat-02.mp4",
    "startSeconds": 39.5,
    "endSeconds": 43.0,
    "momentBucket": "application_moment",
    "roleTag": "product-like application",
    "clipPriority": 2,
    "visualEvidence": "Close-up shot of the creator rubbing the banana peel under her eye and across her cheekbone.",
    "whyThisMomentMatters": "Demonstrates the specific application technique and highlights the 'skincare' aspect of the DIY method.",
    "mumukiReuseNote": "Use this framing to show the ampoule being applied to the under-eye area, emphasizing the product's targeted benefits."
  },
  {
    "id": "7318924509522791710-003",
    "videoId": "7318924509522791710",
    "creator": "@thenaturalnadine",
    "title": "Banana Peel Skincare Scrub",
    "clipPath": "../content/visual-hook-mining/clips/thenaturalnadine__banana-peel-skincare-scrub__7318924509522791710_v3_31flashlite/beat-03.mp4",
    "startSeconds": 47.5,
    "endSeconds": 51.0,
    "momentBucket": "application_moment",
    "roleTag": "product-like application",
    "clipPriority": 3,
    "visualEvidence": "Close-up of the creator rubbing the peel along her jawline and neck area.",
    "whyThisMomentMatters": "Shows the versatility of the application across different facial zones.",
    "mumukiReuseNote": "Show the ampoule being massaged into the jawline to demonstrate lifting or firming benefits."
  },
  {
    "id": "7330117596110392619-006",
    "videoId": "7330117596110392619",
    "creator": "@victoria__benitez",
    "title": "Banana for Skin Girlies",
    "clipPath": "../content/visual-hook-mining/clips/victoria-benitez__banana-for-skin-girlies__7330117596110392619_v3_31flashlite/beat-01.mp4",
    "startSeconds": 6.5,
    "endSeconds": 10.0,
    "momentBucket": "hook_moment",
    "roleTag": "stop-power",
    "clipPriority": 1,
    "visualEvidence": "The creator is holding a banana peel and directly rubbing the inner side of it against her cheek.",
    "whyThisMomentMatters": "This is the most shocking and attention-grabbing action in the video, creating immediate curiosity about the efficacy of banana peels on skin.",
    "mumukiReuseNote": "Use this as a 'don't do this' hook, transitioning to the professional, clean application of the MUMUKI Honey Banana BDRN Ampoule."
  },
  {
    "id": "7330117596110392619-007",
    "videoId": "7330117596110392619",
    "creator": "@victoria__benitez",
    "title": "Banana for Skin Girlies",
    "clipPath": "../content/visual-hook-mining/clips/victoria-benitez__banana-for-skin-girlies__7330117596110392619_v3_31flashlite/beat-02.mp4",
    "startSeconds": 13.0,
    "endSeconds": 16.0,
    "momentBucket": "ingredient_focus",
    "roleTag": "visual-proof",
    "clipPriority": 2,
    "visualEvidence": "Close-up of the creator rubbing the banana peel across her forehead and under-eye area.",
    "whyThisMomentMatters": "It highlights the 'banana for skin' trend and the specific desire for 'glowy' skin, which aligns with the product's benefits.",
    "mumukiReuseNote": "Can be used as a montage clip to show the popularity of banana-based skincare before introducing the product as the superior alternative."
  },
  {
    "id": "7330117596110392619-008",
    "videoId": "7330117596110392619",
    "creator": "@victoria__benitez",
    "title": "Banana for Skin Girlies",
    "clipPath": "../content/visual-hook-mining/clips/victoria-benitez__banana-for-skin-girlies__7330117596110392619_v3_31flashlite/beat-03.mp4",
    "startSeconds": 16.5,
    "endSeconds": 19.5,
    "momentBucket": "ingredient_focus",
    "roleTag": "visual-proof",
    "clipPriority": 3,
    "visualEvidence": "The creator is aggressively rubbing the banana peel over her entire face, showing the texture of the peel against the skin.",
    "whyThisMomentMatters": "Demonstrates the high level of interest in DIY banana skincare, proving the ingredient's appeal to the target audience.",
    "mumukiReuseNote": "Use to contrast the messy DIY approach with the refined, concentrated formula of the MUMUKI ampoule."
  },
  {
    "id": "7331862916603612462-012",
    "videoId": "7331862916603612462",
    "creator": "@sheenaanayaaa",
    "title": "Banana Peel Tightening Test",
    "clipPath": "../content/visual-hook-mining/clips/sheenaanayaaa__banana-peel-tightening-test__7331862916603612462_v3_31flashlite/beat-02.mp4",
    "startSeconds": 5.0,
    "endSeconds": 8.0,
    "momentBucket": "application_moment",
    "roleTag": "visual-action",
    "clipPriority": 2,
    "visualEvidence": "The creator rubs the inside of a banana peel directly onto her cheek and jawline.",
    "whyThisMomentMatters": "Demonstrates the 'DIY' application method that viewers find intriguing.",
    "mumukiReuseNote": "Show the application of the MUMUKI ampoule in a similar sweeping motion to emphasize texture and coverage."
  },
  {
    "id": "7331862916603612462-013",
    "videoId": "7331862916603612462",
    "creator": "@sheenaanayaaa",
    "title": "Banana Peel Tightening Test",
    "clipPath": "../content/visual-hook-mining/clips/sheenaanayaaa__banana-peel-tightening-test__7331862916603612462_v3_31flashlite/beat-03.mp4",
    "startSeconds": 10.5,
    "endSeconds": 13.5,
    "momentBucket": "application_moment",
    "roleTag": "visual-action",
    "clipPriority": 3,
    "visualEvidence": "The creator places pieces of banana peel under her eyes like eye patches.",
    "whyThisMomentMatters": "Creates a 'skincare hack' visual that is highly shareable.",
    "mumukiReuseNote": "Show the ampoule being applied to the under-eye area to highlight its targeted benefits."
  },
  {
    "id": "7331862916603612462-014",
    "videoId": "7331862916603612462",
    "creator": "@sheenaanayaaa",
    "title": "Banana Peel Tightening Test",
    "clipPath": "../content/visual-hook-mining/clips/sheenaanayaaa__banana-peel-tightening-test__7331862916603612462_v3_31flashlite/beat-04.mp4",
    "startSeconds": 16.0,
    "endSeconds": 19.0,
    "momentBucket": "process_moment",
    "roleTag": "visual-action",
    "clipPriority": 4,
    "visualEvidence": "The creator has multiple pieces of banana peel stuck to her face as a mask.",
    "whyThisMomentMatters": "Strong visual impact of a 'DIY mask' that stops the scroll.",
    "mumukiReuseNote": "Show the ampoule applied as a thick, nourishing layer to mimic the 'mask' effect."
  },
  {
    "id": "7331862916603612462-015",
    "videoId": "7331862916603612462",
    "creator": "@sheenaanayaaa",
    "title": "Banana Peel Tightening Test",
    "clipPath": "../content/visual-hook-mining/clips/sheenaanayaaa__banana-peel-tightening-test__7331862916603612462_v3_31flashlite/beat-05.mp4",
    "startSeconds": 26.5,
    "endSeconds": 29.5,
    "momentBucket": "result_moment",
    "roleTag": "skin-payoff",
    "clipPriority": 5,
    "visualEvidence": "Close-up of the creator's face showing smooth, glowing skin after the process.",
    "whyThisMomentMatters": "Provides the 'proof' that the skincare routine works.",
    "mumukiReuseNote": "Show a close-up of skin after applying the MUMUKI ampoule to highlight the glow and texture improvement."
  },
  {
    "id": "7355150760293747998-016",
    "videoId": "7355150760293747998",
    "creator": "@katiejanehughes",
    "title": "Banana Skin Facial",
    "clipPath": "../content/visual-hook-mining/clips/katiejanehughes__banana-skin-facial__7355150760293747998_v3_31flashlite/beat-01.mp4",
    "startSeconds": 0.0,
    "endSeconds": 4.0,
    "momentBucket": "hook_moment",
    "roleTag": "stop-power",
    "clipPriority": 1,
    "visualEvidence": "The creator is rubbing the inside of a banana peel directly onto her cheek.",
    "whyThisMomentMatters": "The unconventional use of a common food item as skincare creates immediate curiosity and stop-power.",
    "mumukiReuseNote": "Use this as a hook for the MUMUKI Honey Banana BDRN Ampoule by showing the product being applied in a similar motion to emphasize the 'natural' ingredient benefit."
  },
  {
    "id": "7355150760293747998-017",
    "videoId": "7355150760293747998",
    "creator": "@katiejanehughes",
    "title": "Banana Skin Facial",
    "clipPath": "../content/visual-hook-mining/clips/katiejanehughes__banana-skin-facial__7355150760293747998_v3_31flashlite/beat-02.mp4",
    "startSeconds": 17.0,
    "endSeconds": 20.0,
    "momentBucket": "application_demonstration",
    "roleTag": "product-like application",
    "clipPriority": 2,
    "visualEvidence": "Close-up of the creator rubbing the banana peel on one side of her face.",
    "whyThisMomentMatters": "The 'half-face' experiment is a classic, highly effective visual trope for demonstrating product efficacy.",
    "mumukiReuseNote": "Replicate the half-face application test with the MUMUKI ampoule to visually prove the glow/tightening effect."
  },
  {
    "id": "7355150760293747998-018",
    "videoId": "7355150760293747998",
    "creator": "@katiejanehughes",
    "title": "Banana Skin Facial",
    "clipPath": "../content/visual-hook-mining/clips/katiejanehughes__banana-skin-facial__7355150760293747998_v3_31flashlite/beat-03.mp4",
    "startSeconds": 54.5,
    "endSeconds": 57.0,
    "momentBucket": "application_demonstration",
    "roleTag": "sensory-experience",
    "clipPriority": 3,
    "visualEvidence": "Close-up of the creator rubbing the peel on her cheek, showing the texture and the way it glides on the skin.",
    "whyThisMomentMatters": "Focuses on the sensory experience of the application, which is crucial for skincare marketing.",
    "mumukiReuseNote": "Capture the texture of the MUMUKI ampoule as it glides on the skin to mimic this satisfying application feel."
  },
  {
    "id": "7427159569874390315-021",
    "videoId": "7427159569874390315",
    "creator": "@duoheadspa",
    "title": "Banana Fruit Facial",
    "clipPath": "../content/visual-hook-mining/clips/duoheadspa__banana-fruit-facial__7427159569874390315_v3_31flashlite/beat-01.mp4",
    "startSeconds": 0.0,
    "endSeconds": 2.0,
    "momentBucket": "hook_moment",
    "roleTag": "stop-power",
    "clipPriority": 1,
    "visualEvidence": "A close-up of a person's face completely covered in thin, circular slices of banana.",
    "whyThisMomentMatters": "The bizarre and visually striking image of a face covered in banana slices creates immediate curiosity and 'stop-scrolling' effect.",
    "mumukiReuseNote": "Use as a visual hook to contrast the 'messy DIY' approach with the clean, professional application of the MUMUKI Honey Banana BDRN Ampoule."
  },
  {
    "id": "7446093862952815918-026",
    "videoId": "7446093862952815918",
    "creator": "@tenishaward1",
    "title": "Honey Comb Facial",
    "clipPath": "../content/visual-hook-mining/clips/tenishaward1__honey-comb-facial__7446093862952815918_v3_31flashlite/beat-01.mp4",
    "startSeconds": 0.0,
    "endSeconds": 3.0,
    "momentBucket": "hook_moment",
    "roleTag": "stop-power",
    "clipPriority": 1,
    "visualEvidence": "The creator is holding a large piece of raw honeycomb and squeezing it directly onto her forehead, with honey dripping down her face.",
    "whyThisMomentMatters": "The raw, messy, and tactile nature of squeezing honeycomb directly onto the face creates an immediate 'what is she doing?' curiosity gap.",
    "mumukiReuseNote": "Use this as a high-impact hook by showing the rich, viscous texture of the MUMUKI ampoule being applied in a similar close-up, satisfying way."
  },
  {
    "id": "7446093862952815918-027",
    "videoId": "7446093862952815918",
    "creator": "@tenishaward1",
    "title": "Honey Comb Facial",
    "clipPath": "../content/visual-hook-mining/clips/tenishaward1__honey-comb-facial__7446093862952815918_v3_31flashlite/beat-02.mp4",
    "startSeconds": 3.0,
    "endSeconds": 6.0,
    "momentBucket": "ingredient_texture",
    "roleTag": "texture-focus",
    "clipPriority": 2,
    "visualEvidence": "Close-up of honey dripping and spreading across the creator's face, showing the sticky, thick consistency.",
    "whyThisMomentMatters": "Highlights the sensory appeal of honey as a skincare ingredient, which is a key selling point for the ampoule.",
    "mumukiReuseNote": "Showcase the ampoule's texture in a similar macro shot to emphasize its richness and quality."
  },
  {
    "id": "7446093862952815918-028",
    "videoId": "7446093862952815918",
    "creator": "@tenishaward1",
    "title": "Honey Comb Facial",
    "clipPath": "../content/visual-hook-mining/clips/tenishaward1__honey-comb-facial__7446093862952815918_v3_31flashlite/beat-03.mp4",
    "startSeconds": 8.0,
    "endSeconds": 11.0,
    "momentBucket": "application_process",
    "roleTag": "application-demo",
    "clipPriority": 3,
    "visualEvidence": "The creator is massaging the honey into her skin with both hands, showing the full coverage of the DIY mask.",
    "whyThisMomentMatters": "Demonstrates the ritualistic aspect of skincare application, which viewers find relaxing and satisfying to watch.",
    "mumukiReuseNote": "Replicate this massage motion with the MUMUKI ampoule to show how it absorbs or glides on the skin."
  },
  {
    "id": "7446093862952815918-029",
    "videoId": "7446093862952815918",
    "creator": "@tenishaward1",
    "title": "Honey Comb Facial",
    "clipPath": "../content/visual-hook-mining/clips/tenishaward1__honey-comb-facial__7446093862952815918_v3_31flashlite/beat-04.mp4",
    "startSeconds": 12.0,
    "endSeconds": 15.0,
    "momentBucket": "skin_payoff",
    "roleTag": "result-focus",
    "clipPriority": 4,
    "visualEvidence": "The creator shows her face after the mask, highlighting a natural, dewy glow.",
    "whyThisMomentMatters": "Provides the 'payoff' that justifies the messy process, proving that the ingredient leads to visible skin improvement.",
    "mumukiReuseNote": "Use this as the 'after' shot to demonstrate the glow provided by the MUMUKI ampoule."
  },
  {
    "id": "7446093862952815918-030",
    "videoId": "7446093862952815918",
    "creator": "@tenishaward1",
    "title": "Honey Comb Facial",
    "clipPath": "../content/visual-hook-mining/clips/tenishaward1__honey-comb-facial__7446093862952815918_v3_31flashlite/beat-05.mp4",
    "startSeconds": 15.0,
    "endSeconds": 17.6,
    "momentBucket": "skin_payoff",
    "roleTag": "result-focus",
    "clipPriority": 5,
    "visualEvidence": "Close-up of the creator smiling and touching her glowing, hydrated skin.",
    "whyThisMomentMatters": "The final result shot confirms the effectiveness of the honey-based skincare routine.",
    "mumukiReuseNote": "Use this as a closing shot to show the final skin texture achieved after using the MUMUKI product."
  },
  {
    "id": "7447707169664879915-031",
    "videoId": "7447707169664879915",
    "creator": "@byzareefa",
    "title": "Banana Peel DIY Mask",
    "clipPath": "../content/visual-hook-mining/clips/byzareefa__banana-peel-diy-mask__7447707169664879915_v3_31flashlite/beat-01.mp4",
    "startSeconds": 1.5,
    "endSeconds": 4.5,
    "momentBucket": "hook_moment",
    "roleTag": "stop-power",
    "clipPriority": 1,
    "visualEvidence": "The creator holds up a banana peel directly to the camera, showing the inside texture.",
    "whyThisMomentMatters": "The direct, close-up reveal of the ingredient creates immediate curiosity and visual intrigue.",
    "mumukiReuseNote": "Use a similar close-up shot of the MUMUKI ampoule or a honey-infused texture to hook the viewer immediately."
  },
  {
    "id": "7447707169664879915-032",
    "videoId": "7447707169664879915",
    "creator": "@byzareefa",
    "title": "Banana Peel DIY Mask",
    "clipPath": "../content/visual-hook-mining/clips/byzareefa__banana-peel-diy-mask__7447707169664879915_v3_31flashlite/beat-02.mp4",
    "startSeconds": 11.0,
    "endSeconds": 14.5,
    "momentBucket": "application_moment",
    "roleTag": "product-like application",
    "clipPriority": 2,
    "visualEvidence": "The creator rubs the inside of the banana peel directly onto her cheek.",
    "whyThisMomentMatters": "Demonstrates the 'DIY skincare' action clearly, which is highly engaging for viewers interested in natural beauty hacks.",
    "mumukiReuseNote": "Replace the banana peel with the application of the MUMUKI ampoule to show the product being massaged into the skin."
  },
  {
    "id": "7447707169664879915-034",
    "videoId": "7447707169664879915",
    "creator": "@byzareefa",
    "title": "Banana Peel DIY Mask",
    "clipPath": "../content/visual-hook-mining/clips/byzareefa__banana-peel-diy-mask__7447707169664879915_v3_31flashlite/beat-04.mp4",
    "startSeconds": 38.5,
    "endSeconds": 42.0,
    "momentBucket": "application_moment",
    "roleTag": "product-like application",
    "clipPriority": 4,
    "visualEvidence": "The creator applies the peel to her chin and jawline area.",
    "whyThisMomentMatters": "Focuses on specific areas of concern, which helps viewers visualize the product's utility.",
    "mumukiReuseNote": "Show the ampoule being applied to the jawline to highlight the lifting or brightening effect."
  },
  {
    "id": "7447707169664879915-035",
    "videoId": "7447707169664879915",
    "creator": "@byzareefa",
    "title": "Banana Peel DIY Mask",
    "clipPath": "../content/visual-hook-mining/clips/byzareefa__banana-peel-diy-mask__7447707169664879915_v3_31flashlite/beat-05.mp4",
    "startSeconds": 53.0,
    "endSeconds": 56.5,
    "momentBucket": "result_moment",
    "roleTag": "skin glow / skin payoff",
    "clipPriority": 5,
    "visualEvidence": "The creator looks directly at the camera with a glowing, hydrated complexion after the treatment.",
    "whyThisMomentMatters": "Provides the 'payoff' shot that validates the efficacy of the ingredient, which is essential for conversion.",
    "mumukiReuseNote": "Use a similar 'after' shot showing the glowing skin result after using the MUMUKI ampoule."
  },
  {
    "id": "7459763407668006152-037",
    "videoId": "7459763407668006152",
    "creator": "@kevinnkylee",
    "title": "Banana Skin Tightening Hack",
    "clipPath": "../content/visual-hook-mining/clips/kevinnkylee__banana-skin-tightening-hack__7459763407668006152_v3_31flashlite/beat-02.mp4",
    "startSeconds": 3.0,
    "endSeconds": 6.0,
    "momentBucket": "application_moment",
    "roleTag": "visual-demonstration",
    "clipPriority": 2,
    "visualEvidence": "The creator rubs the inside of a banana peel directly onto his cheek and forehead.",
    "whyThisMomentMatters": "Direct application of the ingredient to the skin is the core visual hook that validates the DIY skincare angle.",
    "mumukiReuseNote": "Show the texture of the Honey Banana ampoule being applied to the skin in a similar motion to emphasize the 'banana' benefit."
  },
  {
    "id": "7459763407668006152-038",
    "videoId": "7459763407668006152",
    "creator": "@kevinnkylee",
    "title": "Banana Skin Tightening Hack",
    "clipPath": "../content/visual-hook-mining/clips/kevinnkylee__banana-skin-tightening-hack__7459763407668006152_v3_31flashlite/beat-03.mp4",
    "startSeconds": 6.0,
    "endSeconds": 11.0,
    "momentBucket": "application_moment",
    "roleTag": "visual-demonstration",
    "clipPriority": 3,
    "visualEvidence": "The creator continues rubbing the banana peel across his nose, chin, and jawline.",
    "whyThisMomentMatters": "Shows the versatility of the ingredient across different facial zones, reinforcing the 'tightening' claim.",
    "mumukiReuseNote": "Demonstrate the ampoule being massaged into the same facial zones to show ease of use."
  },
  {
    "id": "7459763407668006152-040",
    "videoId": "7459763407668006152",
    "creator": "@kevinnkylee",
    "title": "Banana Skin Tightening Hack",
    "clipPath": "../content/visual-hook-mining/clips/kevinnkylee__banana-skin-tightening-hack__7459763407668006152_v3_31flashlite/beat-05.mp4",
    "startSeconds": 19.0,
    "endSeconds": 26.0,
    "momentBucket": "payoff_moment",
    "roleTag": "result-showcase",
    "clipPriority": 5,
    "visualEvidence": "The creator wipes his face with a tissue and then touches his skin, showing a glowing, smooth texture.",
    "whyThisMomentMatters": "The 'after' shot is essential to prove the efficacy of the ingredient and satisfy the viewer's desire for results.",
    "mumukiReuseNote": "Show the 'glow' payoff after applying the Honey Banana ampoule to demonstrate the product's immediate effect."
  },
  {
    "id": "7545915943940050231-041",
    "videoId": "7545915943940050231",
    "creator": "@jaimesskin",
    "title": "Manuka Honey Face Mask",
    "clipPath": "../content/visual-hook-mining/clips/jaimesskin__manuka-honey-face-mask__7545915943940050231_v3_31flashlite/beat-01.mp4",
    "startSeconds": 0.0,
    "endSeconds": 3.0,
    "momentBucket": "hook_moment",
    "roleTag": "stop-power",
    "clipPriority": 1,
    "visualEvidence": "Close-up of the creator's face completely covered in a thick, golden, sticky honey mask, holding a wooden spoon with honey.",
    "whyThisMomentMatters": "The immediate visual of a thick, sticky, golden mask on the face is highly arresting and signals a DIY skincare routine.",
    "mumukiReuseNote": "Use this as a high-impact hook for the MUMUKI ampoule, showing the product texture being applied similarly."
  },
  {
    "id": "7555933284388146454-046",
    "videoId": "7555933284388146454",
    "creator": "@kriziaraso",
    "title": "Honey Facial Glow",
    "clipPath": "../content/visual-hook-mining/clips/kriziaraso__honey-facial-glow__7555933284388146454_v3_31flashlite/beat-01.mp4",
    "startSeconds": 0.0,
    "endSeconds": 2.5,
    "momentBucket": "hook_moment",
    "roleTag": "stop-power",
    "clipPriority": 1,
    "visualEvidence": "The creator shows a split-screen comparison of her skin with acne (before) and her current clear, glowing skin.",
    "whyThisMomentMatters": "The dramatic before-and-after transformation immediately establishes credibility and high stakes for the viewer.",
    "mumukiReuseNote": "Use a similar split-screen format to show the immediate soothing effect of the MUMUKI ampoule on irritated skin."
  },
  {
    "id": "7555933284388146454-047",
    "videoId": "7555933284388146454",
    "creator": "@kriziaraso",
    "title": "Honey Facial Glow",
    "clipPath": "../content/visual-hook-mining/clips/kriziaraso__honey-facial-glow__7555933284388146454_v3_31flashlite/beat-02.mp4",
    "startSeconds": 4.5,
    "endSeconds": 7.5,
    "momentBucket": "product_application",
    "roleTag": "visual-satisfaction",
    "clipPriority": 2,
    "visualEvidence": "The creator uses a small spatula to drizzle thick, golden honey directly onto her cheek.",
    "whyThisMomentMatters": "The viscous, golden texture of the honey is visually satisfying and highlights the raw ingredient focus.",
    "mumukiReuseNote": "Replicate this 'drip' shot with the MUMUKI ampoule to emphasize its rich, concentrated texture."
  },
  {
    "id": "7555933284388146454-048",
    "videoId": "7555933284388146454",
    "creator": "@kriziaraso",
    "title": "Honey Facial Glow",
    "clipPath": "../content/visual-hook-mining/clips/kriziaraso__honey-facial-glow__7555933284388146454_v3_31flashlite/beat-03.mp4",
    "startSeconds": 7.5,
    "endSeconds": 10.0,
    "momentBucket": "product_application",
    "roleTag": "visual-satisfaction",
    "clipPriority": 3,
    "visualEvidence": "The creator spreads the honey across her face with her fingers, creating a glossy, reflective layer.",
    "whyThisMomentMatters": "Shows the product coverage and the immediate 'glow' effect on the skin.",
    "mumukiReuseNote": "Show the application of the ampoule to demonstrate how it leaves a non-sticky, healthy glow."
  },
  {
    "id": "7555933284388146454-049",
    "videoId": "7555933284388146454",
    "creator": "@kriziaraso",
    "title": "Honey Facial Glow",
    "clipPath": "../content/visual-hook-mining/clips/kriziaraso__honey-facial-glow__7555933284388146454_v3_31flashlite/beat-04.mp4",
    "startSeconds": 10.0,
    "endSeconds": 12.5,
    "momentBucket": "product_application",
    "roleTag": "visual-satisfaction",
    "clipPriority": 4,
    "visualEvidence": "Close-up of the creator massaging the honey into her skin with both hands.",
    "whyThisMomentMatters": "The massage motion implies a self-care ritual, which is highly engaging for skincare audiences.",
    "mumukiReuseNote": "Use a close-up of the massage technique to highlight the absorption and soothing properties of the ampoule."
  },
  {
    "id": "7555933284388146454-050",
    "videoId": "7555933284388146454",
    "creator": "@kriziaraso",
    "title": "Honey Facial Glow",
    "clipPath": "../content/visual-hook-mining/clips/kriziaraso__honey-facial-glow__7555933284388146454_v3_31flashlite/beat-05.mp4",
    "startSeconds": 12.5,
    "endSeconds": 14.6,
    "momentBucket": "result_moment",
    "roleTag": "payoff",
    "clipPriority": 5,
    "visualEvidence": "The creator poses with her face fully coated in honey, looking directly at the camera with a confident expression.",
    "whyThisMomentMatters": "Final shot reinforces the 'DIY skincare' aesthetic and the confidence gained from the routine.",
    "mumukiReuseNote": "End with a 'glowing skin' reveal after using the MUMUKI ampoule to show the final result."
  },
  {
    "id": "7561970033195257101-051",
    "videoId": "7561970033195257101",
    "creator": "@thejenjones",
    "title": "Banana Peel Natural t0x",
    "clipPath": "../content/visual-hook-mining/clips/thejenjones__banana-peel-natural-t0x__7561970033195257101_v3_31flashlite/beat-01.mp4",
    "startSeconds": 0.0,
    "endSeconds": 3.5,
    "momentBucket": "hook_moment",
    "roleTag": "stop-power",
    "clipPriority": 1,
    "visualEvidence": "The creator holds a banana peel directly in front of the camera, showing the inside of the peel.",
    "whyThisMomentMatters": "The immediate visual of a banana peel combined with the bold claim of 'natural botox' creates high curiosity and stop-power.",
    "mumukiReuseNote": "Can be adapted by showing the MUMUKI Honey Banana BDRN Ampoule bottle next to a fresh banana to establish the ingredient connection immediately."
  },
  {
    "id": "7561970033195257101-052",
    "videoId": "7561970033195257101",
    "creator": "@thejenjones",
    "title": "Banana Peel Natural t0x",
    "clipPath": "../content/visual-hook-mining/clips/thejenjones__banana-peel-natural-t0x__7561970033195257101_v3_31flashlite/beat-02.mp4",
    "startSeconds": 12.5,
    "endSeconds": 16.0,
    "momentBucket": "application_moment",
    "roleTag": "visual-demonstration",
    "clipPriority": 2,
    "visualEvidence": "The creator rubs the inside of the banana peel directly onto her cheek and under-eye area.",
    "whyThisMomentMatters": "Shows the direct application of the ingredient to the skin, which is a highly engaging 'DIY' visual.",
    "mumukiReuseNote": "Replace the banana peel with the application of the MUMUKI Ampoule to show the product being applied to the same facial zones."
  },
  {
    "id": "7561970033195257101-053",
    "videoId": "7561970033195257101",
    "creator": "@thejenjones",
    "title": "Banana Peel Natural t0x",
    "clipPath": "../content/visual-hook-mining/clips/thejenjones__banana-peel-natural-t0x__7561970033195257101_v3_31flashlite/beat-03.mp4",
    "startSeconds": 18.5,
    "endSeconds": 21.0,
    "momentBucket": "application_moment",
    "roleTag": "visual-demonstration",
    "clipPriority": 3,
    "visualEvidence": "The creator rubs the banana peel across her forehead, demonstrating a full-face application technique.",
    "whyThisMomentMatters": "Demonstrates the ease of use and the 'skincare routine' aspect of the ingredient.",
    "mumukiReuseNote": "Use this as a reference for the 'application flow' of the MUMUKI Ampoule, showing a smooth, satisfying application motion."
  },
  {
    "id": "7561970033195257101-054",
    "videoId": "7561970033195257101",
    "creator": "@thejenjones",
    "title": "Banana Peel Natural t0x",
    "clipPath": "../content/visual-hook-mining/clips/thejenjones__banana-peel-natural-t0x__7561970033195257101_v3_31flashlite/beat-04.mp4",
    "startSeconds": 45.5,
    "endSeconds": 49.0,
    "momentBucket": "payoff_moment",
    "roleTag": "skin-glow",
    "clipPriority": 4,
    "visualEvidence": "The creator applies the product to her face and pats it in, showing her skin looking hydrated and glowing.",
    "whyThisMomentMatters": "Provides the 'payoff' or result of the skincare routine, which is essential for conversion.",
    "mumukiReuseNote": "Directly mirror this shot with the MUMUKI Ampoule to showcase the 'instant glow' benefit of the product."
  },
  {
    "id": "7579824086315011359-056",
    "videoId": "7579824086315011359",
    "creator": "@drewcanole",
    "title": "DIY Honey Face Mask",
    "clipPath": "../content/visual-hook-mining/clips/drewcanole__diy-honey-face-mask__7579824086315011359_v3_31flashlite/beat-01.mp4",
    "startSeconds": 0.0,
    "endSeconds": 4.0,
    "momentBucket": "hook_moment",
    "roleTag": "stop-power",
    "clipPriority": 1,
    "visualEvidence": "A woman is applying a thick, golden honey mask onto her face using a spoon, with visible acne spots on her skin.",
    "whyThisMomentMatters": "The immediate visual of applying a sticky, natural ingredient directly to the face creates high curiosity and 'gross-but-satisfying' appeal.",
    "mumukiReuseNote": "Use this as a direct hook for the MUMUKI ampoule application, showing the texture being spread on the skin."
  },
  {
    "id": "7579824086315011359-057",
    "videoId": "7579824086315011359",
    "creator": "@drewcanole",
    "title": "DIY Honey Face Mask",
    "clipPath": "../content/visual-hook-mining/clips/drewcanole__diy-honey-face-mask__7579824086315011359_v3_31flashlite/beat-02.mp4",
    "startSeconds": 6.0,
    "endSeconds": 9.0,
    "momentBucket": "texture_shot",
    "roleTag": "sensory-appeal",
    "clipPriority": 2,
    "visualEvidence": "Close-up of a honey dipper dripping thick, golden raw honey.",
    "whyThisMomentMatters": "High-quality texture shots of natural ingredients are visually satisfying and build trust in the product's purity.",
    "mumukiReuseNote": "Create a similar high-definition macro shot of the MUMUKI ampoule texture to emphasize its richness."
  },
  {
    "id": "7579824086315011359-058",
    "videoId": "7579824086315011359",
    "creator": "@drewcanole",
    "title": "DIY Honey Face Mask",
    "clipPath": "../content/visual-hook-mining/clips/drewcanole__diy-honey-face-mask__7579824086315011359_v3_31flashlite/beat-03.mp4",
    "startSeconds": 24.0,
    "endSeconds": 27.0,
    "momentBucket": "application_shot",
    "roleTag": "product-application",
    "clipPriority": 3,
    "visualEvidence": "A woman gently massaging a white, creamy substance into her skin with her fingertips.",
    "whyThisMomentMatters": "Shows the tactile experience of skincare application, which is essential for demonstrating the 'ritual' aspect of using an ampoule.",
    "mumukiReuseNote": "Replicate this exact massage technique with the MUMUKI ampoule to show how it absorbs into the skin."
  },
  {
    "id": "7579824086315011359-059",
    "videoId": "7579824086315011359",
    "creator": "@drewcanole",
    "title": "DIY Honey Face Mask",
    "clipPath": "../content/visual-hook-mining/clips/drewcanole__diy-honey-face-mask__7579824086315011359_v3_31flashlite/beat-04.mp4",
    "startSeconds": 27.0,
    "endSeconds": 30.0,
    "momentBucket": "payoff_shot",
    "roleTag": "skin-glow",
    "clipPriority": 4,
    "visualEvidence": "Close-up of a woman's face showing a dewy, glowing complexion after the skincare routine.",
    "whyThisMomentMatters": "The 'glow' payoff is the ultimate goal for the viewer and provides the necessary social proof for the skincare routine.",
    "mumukiReuseNote": "Use this as the 'after' result shot to showcase the immediate radiance provided by the MUMUKI ampoule."
  },
  {
    "id": "7593798567966297355-061",
    "videoId": "7593798567966297355",
    "creator": "@shamiebirungi19",
    "title": "Honey Skin Glow Hack",
    "clipPath": "../content/visual-hook-mining/clips/shamiebirungi19__honey-skin-glow-hack__7593798567966297355_v3_31flashlite/beat-01.mp4",
    "startSeconds": 0.0,
    "endSeconds": 3.5,
    "momentBucket": "hook_moment",
    "roleTag": "stop-power",
    "clipPriority": 1,
    "visualEvidence": "Honey is being poured directly from a bottle onto the center of the creator's forehead.",
    "whyThisMomentMatters": "The immediate, messy, and satisfying visual of pouring honey directly onto the face is a high-retention hook.",
    "mumukiReuseNote": "Use this as a 'texture hook' to show the richness of the MUMUKI ampoule, replacing honey with the product texture."
  },
  {
    "id": "7593798567966297355-062",
    "videoId": "7593798567966297355",
    "creator": "@shamiebirungi19",
    "title": "Honey Skin Glow Hack",
    "clipPath": "../content/visual-hook-mining/clips/shamiebirungi19__honey-skin-glow-hack__7593798567966297355_v3_31flashlite/beat-02.mp4",
    "startSeconds": 3.5,
    "endSeconds": 6.0,
    "momentBucket": "action_moment",
    "roleTag": "visual-engagement",
    "clipPriority": 4,
    "visualEvidence": "The honey drips down the creator's nose and she licks it off, showing the raw nature of the ingredient.",
    "whyThisMomentMatters": "The interaction with the ingredient makes the DIY process feel authentic and relatable.",
    "mumukiReuseNote": "Not reusable as is, but the 'drip' visual can be adapted to show the ampoule's viscosity."
  },
  {
    "id": "7593798567966297355-063",
    "videoId": "7593798567966297355",
    "creator": "@shamiebirungi19",
    "title": "Honey Skin Glow Hack",
    "clipPath": "../content/visual-hook-mining/clips/shamiebirungi19__honey-skin-glow-hack__7593798567966297355_v3_31flashlite/beat-03.mp4",
    "startSeconds": 6.5,
    "endSeconds": 10.0,
    "momentBucket": "application_moment",
    "roleTag": "product-application",
    "clipPriority": 2,
    "visualEvidence": "The creator uses her fingers to spread the thick, sticky honey across her entire face.",
    "whyThisMomentMatters": "Shows the full coverage application process, which is essential for skincare tutorials.",
    "mumukiReuseNote": "Replicate this application motion with the MUMUKI ampoule to demonstrate ease of spread and coverage."
  },
  {
    "id": "7593798567966297355-064",
    "videoId": "7593798567966297355",
    "creator": "@shamiebirungi19",
    "title": "Honey Skin Glow Hack",
    "clipPath": "../content/visual-hook-mining/clips/shamiebirungi19__honey-skin-glow-hack__7593798567966297355_v3_31flashlite/beat-04.mp4",
    "startSeconds": 13.5,
    "endSeconds": 17.18,
    "momentBucket": "payoff_moment",
    "roleTag": "skin-glow",
    "clipPriority": 3,
    "visualEvidence": "The creator points to her cheek, highlighting the glossy, hydrated, and glowing finish of her skin.",
    "whyThisMomentMatters": "This is the 'payoff' that justifies the entire process; it proves the 'glow' result.",
    "mumukiReuseNote": "Essential for the 'After' shot of the MUMUKI ampoule to show the immediate skin radiance."
  },
  {
    "id": "7603074530570980638-065",
    "videoId": "7603074530570980638",
    "creator": "@bithhnh387",
    "title": "Frozen Banana Skincare",
    "clipPath": "../content/visual-hook-mining/clips/bithhnh387__frozen-banana-skincare__7603074530570980638_v3_31flashlite/beat-01.mp4",
    "startSeconds": 34.0,
    "endSeconds": 37.0,
    "momentBucket": "application_moment",
    "roleTag": "product-like application",
    "clipPriority": 1,
    "visualEvidence": "A brush is applying a thick, golden, honey-like mask onto a person's face.",
    "whyThisMomentMatters": "Demonstrates the satisfying, luxurious application of a honey-based mask, which is highly relevant to the MUMUKI product texture.",
    "mumukiReuseNote": "Use this as a direct visual reference for how to showcase the texture and application of the MUMUKI Honey Banana BDRN Ampoule."
  },
  {
    "id": "7603074530570980638-066",
    "videoId": "7603074530570980638",
    "creator": "@bithhnh387",
    "title": "Frozen Banana Skincare",
    "clipPath": "../content/visual-hook-mining/clips/bithhnh387__frozen-banana-skincare__7603074530570980638_v3_31flashlite/beat-02.mp4",
    "startSeconds": 25.0,
    "endSeconds": 29.0,
    "momentBucket": "texture_moment",
    "roleTag": "honey texture / sticky texture",
    "clipPriority": 2,
    "visualEvidence": "Honey is being poured from a spoon into a glass container, showing its viscous, golden texture.",
    "whyThisMomentMatters": "Visualizes the key ingredient (honey) in a way that emphasizes its premium, sticky, and nourishing quality.",
    "mumukiReuseNote": "Can be used as a B-roll shot to highlight the honey ingredient in the MUMUKI formula."
  },
  {
    "id": "7603074530570980638-067",
    "videoId": "7603074530570980638",
    "creator": "@bithhnh387",
    "title": "Frozen Banana Skincare",
    "clipPath": "../content/visual-hook-mining/clips/bithhnh387__frozen-banana-skincare__7603074530570980638_v3_31flashlite/beat-03.mp4",
    "startSeconds": 43.0,
    "endSeconds": 46.0,
    "momentBucket": "application_moment",
    "roleTag": "face close-up",
    "clipPriority": 3,
    "visualEvidence": "Close-up of the mask being smoothed over the skin, showing the texture and coverage.",
    "whyThisMomentMatters": "Shows the product sitting on the skin, which helps the viewer visualize the skincare experience.",
    "mumukiReuseNote": "Good for demonstrating the 'masking' or 'treatment' aspect of the ampoule."
  },
  {
    "id": "7615701080982211853-070",
    "videoId": "7615701080982211853",
    "creator": "@tenishaward1",
    "title": "Brighter Clearer Skin",
    "clipPath": "../content/visual-hook-mining/clips/tenishaward1__brighter-clearer-skin__7615701080982211853_v3_31flashlite/beat-01.mp4",
    "startSeconds": 0.0,
    "endSeconds": 2.5,
    "momentBucket": "hook_moment",
    "roleTag": "stop-power",
    "clipPriority": 1,
    "visualEvidence": "The creator is applying a thick, bright yellow paste onto her face with a brush, covering her entire face.",
    "whyThisMomentMatters": "The high-contrast yellow color and the immediate application create a strong visual hook that stops the scroll.",
    "mumukiReuseNote": "Use this as a direct visual hook for the MUMUKI ampoule application to show texture and coverage."
  },
  {
    "id": "7615701080982211853-071",
    "videoId": "7615701080982211853",
    "creator": "@tenishaward1",
    "title": "Brighter Clearer Skin",
    "clipPath": "../content/visual-hook-mining/clips/tenishaward1__brighter-clearer-skin__7615701080982211853_v3_31flashlite/beat-02.mp4",
    "startSeconds": 2.5,
    "endSeconds": 5.0,
    "momentBucket": "product_application",
    "roleTag": "texture-demonstration",
    "clipPriority": 2,
    "visualEvidence": "Close-up of the brush spreading the smooth, thick yellow paste across the cheek and forehead.",
    "whyThisMomentMatters": "Demonstrates the satisfying, smooth texture of the DIY mask, which is highly relevant to the texture of an ampoule.",
    "mumukiReuseNote": "Show the MUMUKI ampoule being spread on the skin in a similar close-up to highlight its consistency."
  },
  {
    "id": "7615701080982211853-072",
    "videoId": "7615701080982211853",
    "creator": "@tenishaward1",
    "title": "Brighter Clearer Skin",
    "clipPath": "../content/visual-hook-mining/clips/tenishaward1__brighter-clearer-skin__7615701080982211853_v3_31flashlite/beat-03.mp4",
    "startSeconds": 5.0,
    "endSeconds": 7.5,
    "momentBucket": "product_application",
    "roleTag": "satisfying-application",
    "clipPriority": 3,
    "visualEvidence": "The creator is carefully applying the mask around the nose and mouth area with a brush.",
    "whyThisMomentMatters": "The precision application is visually satisfying and mimics the professional application of skincare products.",
    "mumukiReuseNote": "Use this to show the precision application of the MUMUKI ampoule around targeted areas."
  },
  {
    "id": "7615701080982211853-073",
    "videoId": "7615701080982211853",
    "creator": "@tenishaward1",
    "title": "Brighter Clearer Skin",
    "clipPath": "../content/visual-hook-mining/clips/tenishaward1__brighter-clearer-skin__7615701080982211853_v3_31flashlite/beat-04.mp4",
    "startSeconds": 7.5,
    "endSeconds": 9.9,
    "momentBucket": "result_moment",
    "roleTag": "skin-payoff",
    "clipPriority": 4,
    "visualEvidence": "The creator touches her clean, glowing skin, showing the final result after the mask.",
    "whyThisMomentMatters": "Provides the 'payoff' or the desired outcome that viewers are looking for in skincare content.",
    "mumukiReuseNote": "Show the 'after' glow of the skin after using the MUMUKI ampoule to prove efficacy."
  },
  {
    "id": "7618385031932808462-074",
    "videoId": "7618385031932808462",
    "creator": "@scottyscheller",
    "title": "Honey Health Hook",
    "clipPath": "../content/visual-hook-mining/clips/scottyscheller__honey-health-hook__7618385031932808462_v3_31flashlite/beat-01.mp4",
    "startSeconds": 0.0,
    "endSeconds": 2.5,
    "momentBucket": "hook_moment",
    "roleTag": "stop-power",
    "clipPriority": 1,
    "visualEvidence": "Close-up of a spoon lifting a thick, viscous, golden honey from a jar, creating a long, slow drip.",
    "whyThisMomentMatters": "The extreme close-up and the satisfying, thick texture of the honey immediately grab attention.",
    "mumukiReuseNote": "Use a similar close-up shot of the honey-infused ampoule texture to demonstrate its richness and quality."
  },
  {
    "id": "7618385031932808462-075",
    "videoId": "7618385031932808462",
    "creator": "@scottyscheller",
    "title": "Honey Health Hook",
    "clipPath": "../content/visual-hook-mining/clips/scottyscheller__honey-health-hook__7618385031932808462_v3_31flashlite/beat-02.mp4",
    "startSeconds": 12.0,
    "endSeconds": 14.5,
    "momentBucket": "texture_demonstration",
    "roleTag": "texture-appeal",
    "clipPriority": 2,
    "visualEvidence": "The creator holds the jar up to the camera, showing the honey dripping slowly off the spoon.",
    "whyThisMomentMatters": "Highlights the premium, raw, and natural quality of the ingredient.",
    "mumukiReuseNote": "Show the ampoule's texture dripping from a dropper to emphasize its concentrated formula."
  },
  {
    "id": "7618385031932808462-077",
    "videoId": "7618385031932808462",
    "creator": "@scottyscheller",
    "title": "Honey Health Hook",
    "clipPath": "../content/visual-hook-mining/clips/scottyscheller__honey-health-hook__7618385031932808462_v3_31flashlite/beat-04.mp4",
    "startSeconds": 29.5,
    "endSeconds": 32.0,
    "momentBucket": "texture_demonstration",
    "roleTag": "texture-appeal",
    "clipPriority": 4,
    "visualEvidence": "The creator holds the spoon with the honey dripping down, focusing on the slow, continuous flow.",
    "whyThisMomentMatters": "The slow-motion effect of the honey flow is visually hypnotic and emphasizes purity.",
    "mumukiReuseNote": "Create a slow-motion shot of the ampoule serum dripping to convey a sense of luxury and potency."
  },
  {
    "id": "7621189679148272928-079",
    "videoId": "7621189679148272928",
    "creator": "@iamedsonbrandao",
    "title": "Frozen Banana Lift Hack",
    "clipPath": "../content/visual-hook-mining/clips/iamedsonbrandao__frozen-banana-lift-hack__7621189679148272928_v3_31flashlite/beat-01.mp4",
    "startSeconds": 0.0,
    "endSeconds": 3.0,
    "momentBucket": "hook_moment",
    "roleTag": "stop-power",
    "clipPriority": 1,
    "visualEvidence": "The creator holds two halves of a frozen, dark-spotted banana directly in front of the camera.",
    "whyThisMomentMatters": "The visual of a frozen banana used for skincare is highly unconventional and immediately grabs attention.",
    "mumukiReuseNote": "Use a similar 'What is this?' opening shot with the MUMUKI ampoule to create curiosity."
  },
  {
    "id": "7621189679148272928-080",
    "videoId": "7621189679148272928",
    "creator": "@iamedsonbrandao",
    "title": "Frozen Banana Lift Hack",
    "clipPath": "../content/visual-hook-mining/clips/iamedsonbrandao__frozen-banana-lift-hack__7621189679148272928_v3_31flashlite/beat-02.mp4",
    "startSeconds": 3.5,
    "endSeconds": 6.5,
    "momentBucket": "application_moment",
    "roleTag": "visual-action",
    "clipPriority": 2,
    "visualEvidence": "The creator rubs the frozen banana halves along his jawline in a lifting motion.",
    "whyThisMomentMatters": "Demonstrates a clear, actionable 'hack' that viewers can mimic, proving the interest in DIY banana skincare.",
    "mumukiReuseNote": "Show the application of the MUMUKI ampoule using a similar upward lifting motion on the jawline."
  },
  {
    "id": "7621189679148272928-081",
    "videoId": "7621189679148272928",
    "creator": "@iamedsonbrandao",
    "title": "Frozen Banana Lift Hack",
    "clipPath": "../content/visual-hook-mining/clips/iamedsonbrandao__frozen-banana-lift-hack__7621189679148272928_v3_31flashlite/beat-03.mp4",
    "startSeconds": 10.5,
    "endSeconds": 13.0,
    "momentBucket": "application_moment",
    "roleTag": "visual-action",
    "clipPriority": 3,
    "visualEvidence": "The creator rubs the flat surface of the frozen banana directly onto his cheek.",
    "whyThisMomentMatters": "Direct skin contact with the ingredient highlights the 'skincare' aspect of the hack.",
    "mumukiReuseNote": "Show the ampoule being applied directly to the cheek to emphasize hydration."
  },
  {
    "id": "7621189679148272928-082",
    "videoId": "7621189679148272928",
    "creator": "@iamedsonbrandao",
    "title": "Frozen Banana Lift Hack",
    "clipPath": "../content/visual-hook-mining/clips/iamedsonbrandao__frozen-banana-lift-hack__7621189679148272928_v3_31flashlite/beat-04.mp4",
    "startSeconds": 17.0,
    "endSeconds": 20.0,
    "momentBucket": "application_moment",
    "roleTag": "visual-action",
    "clipPriority": 4,
    "visualEvidence": "The creator presses the frozen banana halves under his eyes.",
    "whyThisMomentMatters": "Targets a specific pain point (dark circles) with a simple visual action.",
    "mumukiReuseNote": "Show the ampoule being tapped gently under the eyes to address dark circles."
  },
  {
    "id": "7621189679148272928-083",
    "videoId": "7621189679148272928",
    "creator": "@iamedsonbrandao",
    "title": "Frozen Banana Lift Hack",
    "clipPath": "../content/visual-hook-mining/clips/iamedsonbrandao__frozen-banana-lift-hack__7621189679148272928_v3_31flashlite/beat-05.mp4",
    "startSeconds": 26.5,
    "endSeconds": 29.5,
    "momentBucket": "application_moment",
    "roleTag": "visual-action",
    "clipPriority": 5,
    "visualEvidence": "The creator rubs the banana on his neck in an upward motion.",
    "whyThisMomentMatters": "Focuses on the 'glow' result, which is a key benefit for skincare products.",
    "mumukiReuseNote": "Show the ampoule being applied to the neck to demonstrate the 'glow' effect."
  },
  {
    "id": "7627186004625018134-084",
    "videoId": "7627186004625018134",
    "creator": "@zack.chug",
    "title": "Banana vs t0x Hook",
    "clipPath": "../content/visual-hook-mining/clips/zack-chug__banana-vs-t0x-hook__7627186004625018134_v3_31flashlite/beat-01.mp4",
    "startSeconds": 6.5,
    "endSeconds": 9.0,
    "momentBucket": "hook_moment",
    "roleTag": "stop-power",
    "clipPriority": 1,
    "visualEvidence": "The creator is aggressively rubbing a banana peel directly onto his face, with mashed banana residue sticking to his skin.",
    "whyThisMomentMatters": "High visual shock value; immediately establishes the DIY skincare angle with a relatable, slightly messy action.",
    "mumukiReuseNote": "Use this as a 'don't do this, do this instead' transition to introduce the MUMUKI ampoule as a cleaner, more effective alternative."
  }
];
